import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import ReduxProvider from '@/redux/provider'
import WrapperContainer from '@/components/wrapper-container'
import { CssBaseline } from '@mui/material'
import NavbarMenu from '@/components/navbar-menu'
import GlobalAlert from '@/components/global-alert'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ReduxProvider>
                    <CssBaseline />
                    <NavbarMenu />
                    <WrapperContainer>{children}</WrapperContainer>
                </ReduxProvider>
            </body>
        </html>
    )
}
